
import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{CalendarPlus,Upload,Save,Trash2,RotateCcw,LogIn,Cloud,Download,ShieldCheck,AlertTriangle,Lock}from"lucide-react";
import{getDocument,GlobalWorkerOptions}from"pdfjs-dist";
import pdfWorker from"pdfjs-dist/build/pdf.worker.mjs?url";
import"./style.css";
GlobalWorkerOptions.workerSrc=pdfWorker;

const CID=import.meta.env.VITE_GOOGLE_CLIENT_ID||"";
const SCOPE="https://www.googleapis.com/auth/calendar";
const CAL="SemperPlan", TZ="Europe/Berlin", STORE="semperplan.v9.prefs";
const WORKS=["Parsifal","Carmen","Elias","Giovanni","Don Giovanni","Traviata","La Traviata","Zauberflöte","Zauberfloete","Strawinsky","Opernball","Karmelitinnen","Konzert","Elektra","Rosenkavalier","Tosca","Bohème","Boheme","Aida","Nabucco","Turandot","Tannhäuser","Lohengrin","Meistersinger","Fidelio","Freischütz","Freischuetz"];
const MON={januar:"01",februar:"02","märz":"03",maerz:"03",april:"04",mai:"05",juni:"06",juli:"07",august:"08",september:"09",oktober:"10",november:"11",dezember:"12"};
const WDATE=/^(Montag|Dienstag|Mittwoch|Donnerstag|Freitag|Samstag|Sonntag),?\s*(\d{1,2})\.\s*([A-Za-zÄÖÜäöü]+)\s*(20\d{2})/i;
const MLINE=/^(Mo|Di|Mi|Do|Fr|Sa|So)\s+(\d{1,2})\.(\d{1,2})\.\s*(.*)$/i;
const TSTART=/^(\d{1,2})[.:](\d{2})\s+(.+)$/;
const TANY=/(\d{1,2})[.:](\d{2})/g;
const COACH=/\s+(Becker\/Kim|Hoffmann\/Kim|Hoffmann\/Becker\/Kim|Gatti\/Becker\/Kim|Becker|Kim|Hoffmann|Gatti|Patsalidou|Lindner)$/i;

function c(x){return String(x||"").replace(/\s+/g," ").trim()}
function p(n){return String(n).padStart(2,"0")}
function norm(x){return c(x).toLowerCase().replace(/ä/g,"ae").replace(/ö/g,"oe").replace(/ü/g,"ue").replace(/ß/g,"ss")}
function nw(w){let v=c(w);if(/zauberfloete/i.test(v))return"Zauberflöte";if(/boheme/i.test(v))return"Bohème";return v}
function nextDay(d){let x=new Date(d+"T00:00:00");x.setDate(x.getDate()+1);return x.toISOString().slice(0,10)}
function add(d,t,min){let[h,m]=t.split(":").map(Number),x=new Date(`${d}T${p(h)}:${p(m)}:00`);x.setMinutes(x.getMinutes()+min);return`${p(x.getHours())}:${p(x.getMinutes())}`}
function dur(txt){let s=norm(txt);if(/nachstudium/.test(s))return 60;if(/mus\.\s*probe|mus\.\s*proben/.test(s))return 120;if(/(^|\s)probe(\s|$)/.test(s)&&!/\b(bp|bo|kp|khp|ohp|gp)\b/.test(s))return 120;return 180}
function gender(txt){let s=norm(txt);if(/alle\s+herren|\bherren\b|maenner|manner/.test(s))return"남자";if(/alle\s+damen|\bdamen\b|frauen|blumenmaedchen|blumenmadchen/.test(s))return"여자";if(/alle|alle\s+eingeteilten|chor tutti|sinfoniechor/.test(s))return"전체";return"개별/기타"}
function partOk(txt,part){let s=norm(txt),pt=norm(part||"Tenor");if(!pt)return false;if(/tenor/.test(pt))return/(tenor|tenore|ténor|herren|alle herren)/i.test(s);return s.includes(pt)}
function nameOk(ev,prof){let hay=norm(`${ev.raw} ${ev.title} ${ev.target} ${ev.group}`);return[prof.firstName,prof.lastName].map(norm).filter(x=>x.length>=2).some(x=>hay.includes(x))}
function work(txt,custom=[]){let t=c(txt),arr=[...custom,...WORKS].filter(Boolean);for(let w of arr){let e=w.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");if(new RegExp(`(^|\\s|[-/])${e}(\\s|$|[-/])`,"i").test(t))return nw(w)}let n=t.match(/Nachstudium\s+([A-Za-zÄÖÜäöü0-9.]+)/i);if(n)return nw(n[1]);let code=t.match(/\b(BP|BO|KP|KHP|OHP|GP)\s+([A-Za-zÄÖÜäöü0-9.]+)/i);if(code)return nw(code[2]);let left=t.split(" - ")[0].trim().split(/\s+/).filter(Boolean);return nw(left[left.length-1]||"Dienst")}
function prefix(txt){let raw=c(txt),s=norm(raw),m=raw.match(/\b(KHP|OHP|GP|BP|BO|KP)\b/i);if(m)return m[1].toUpperCase();if(/szen\.\s*probe|szenische\s*probe/.test(s))return"sP";if(/mus\.\s*probe|mus\.\s*proben/.test(s))return"mP";if(/(^|\s)probe(\s|$)/.test(s))return"P";if(/nachstudium/.test(s))return"Nachstudium";return"Vs"}
function title(ev){if(ev.kind==="free")return"🔴 chorfrei";if(ev.kind==="halfAM")return"🔴 1/2 chorfrei 오전";if(ev.kind==="halfPM")return"🔴 1/2 chorfrei 오후";let pr=prefix(ev.raw);if(pr==="Nachstudium")return`Nachstudium ${ev.work}`;if(pr==="Vs")return`Vs ${ev.work}`;return`${pr} ${ev.work}`}
function rmCoach(t){let r=c(t);for(let i=0;i<3;i++)r=r.replace(COACH,"").trim();return r}
function weeklyDetail(txt,custom){let a=c(txt).split(/\s+/),loc=a[0]||"",body=a.slice(1).join(" "),no=rmCoach(body),[left,target=""]=no.split(/\s+-\s+/),wk=work(left,custom),g=gender(`${left} ${target}`);return{loc,left:c(left),target:c(target),wk,g,no}}
function id(){return"ev-"+Date.now()+"-"+Math.random().toString(36).slice(2)}
function stable(ev){return`${ev.date}_${ev.start||"all"}_${ev.end||"all"}_${ev.title}_${ev.location}`.toLowerCase().replace(/[^a-z0-9가-힣]+/gi,"-").replace(/^-+|-+$/g,"")}
function lkey(ev){return ev.allDay?`${ev.date}|ALLDAY`:`${ev.date}|${ev.start}|${ev.end}`}
function gkey(g){let s=g.start?.dateTime||g.start?.date||"",e=g.end?.dateTime||g.end?.date||"";return(g.start?.date&&!g.start?.dateTime)?`${s}|ALLDAY`:`${s.slice(0,16)}|${e.slice(0,16)}`}
function gid(g){let x=g.extendedProperties?.private?.semperPlanId;if(x)return x;let m=(g.description||"").match(/SemperPlan-ID:\s*([^\n]+)/);return m?m[1].trim():""}
function range(events){let ds=events.map(e=>e.date).filter(Boolean).sort();if(!ds.length)return null;let min=ds[0],max=ds[ds.length-1],mx=nextDay(max);return{min,max,timeMin:`${min}T00:00:00+01:00`,timeMax:`${mx}T00:00:00+01:00`}}
function sourceLabel(t){return t==="weekly"?"주간":"월간"}

function makeEv({date,start="",end="",allDay=false,raw="",work:workName="",location="",target="",group="",gender:g="",kind="work",source}){let ev={id:id(),date,start,end,allDay,raw,title:"",work:workName,location,target,group,gender:g,kind,sourceType:source.type,sourceName:source.name,uploadIndex:source.idx};ev.title=title(ev);return ev}
function parseDateHeader(text){let m=c(text).match(WDATE);return m?`${m[4]}-${MON[m[3].toLowerCase()]||"01"}-${p(m[2])}`:""}
function rows(items){let map=new Map();for(let it of items){let k=Math.round(it.y/7)*7;if(!map.has(k))map.set(k,[]);map.get(k).push(it)}return[...map.entries()].sort((a,b)=>b[0]-a[0]).map(([y,row])=>{row.sort((a,b)=>a.x-b.x);let text=c(row.map(i=>i.str).join(" ")),x=Math.min(...row.map(i=>i.x)),mx=Math.max(...row.map(i=>i.x+i.w));return{text,x,y,cx:x+(mx-x)/2}}).filter(r=>r.text)}
function splitTimes(text){let ms=[...text.matchAll(TANY)];if(ms.length<=1)return[text];return ms.map((m,i)=>c(text.slice(m.index,ms[i+1]?.index??text.length))).filter(Boolean)}
function monthly(rows,source,custom){let year=(source.name.match(/(20\d{2})/)||[])[1]||String(new Date().getFullYear()),out=[];for(let r of rows){let m=r.text.match(MLINE);if(!m)continue;let date=`${year}-${p(m[3])}-${p(m[2])}`,rest=c(m[4]),day=[];for(let seg of splitTimes(rest)){let mt=seg.match(TSTART);if(!mt)continue;let st=`${p(mt[1])}:${mt[2]}`,wk=work(mt[3],custom),g=gender(mt[3]);day.push(makeEv({date,start:st,end:add(date,st,dur(seg)),raw:seg,work:wk,group:g,gender:g,source}))}let half=/1\/2\s*chorfrei/i.test(rest),full=/\bchorfrei\b/i.test(rest)&&!half;if(half){let first=[...rest.matchAll(TANY)][0],kind="halfAM",st="10:00",en="11:00";if(first&&Number(first[1])<=13){kind="halfPM";st="18:00";en="19:00"}out.push(makeEv({date,start:st,end:en,raw:rest,work:"chorfrei",group:"chorfrei",gender:"전체",kind,source}))}else if(full)out.push(makeEv({date,allDay:true,raw:rest,work:"chorfrei",group:"chorfrei",gender:"전체",kind:"free",source}));out.push(...day)}return out}
function weekly(rows,source,custom){let dates=rows.map(r=>({r,date:parseDateHeader(r.text)})).filter(x=>x.date),out=[];function near(r){if(!dates.length)return"";return[...dates].sort((a,b)=>Math.abs(a.r.cx-r.cx)-Math.abs(b.r.cx-r.cx))[0].date}for(let r of rows){if(parseDateHeader(r.text))continue;let date=near(r);if(!date)continue;if(/\bchorfrei\b/i.test(r.text)){out.push(makeEv({date,allDay:true,raw:r.text,work:"chorfrei",group:"chorfrei",gender:"전체",kind:"free",source}));continue}for(let seg of splitTimes(r.text)){let m=seg.match(TSTART);if(!m)continue;let st=`${p(m[1])}:${m[2]}`,d=weeklyDetail(m[3],custom);out.push(makeEv({date,start:st,end:add(date,st,dur(seg)),raw:seg,work:d.wk,location:d.loc,target:d.target,group:d.g,gender:d.g,source}))}}return out}
async function parsePdf(file,type,idx,custom){let buf=await file.arrayBuffer(),pdf=await getDocument({data:buf}).promise,all=[];for(let n=1;n<=pdf.numPages;n++){let pg=await pdf.getPage(n),tc=await pg.getTextContent();let items=tc.items.map(i=>({str:c(i.str),x:i.transform[4],y:i.transform[5],w:i.width||10})).filter(i=>i.str);all=all.concat(rows(items))}let source={name:file.name,type,idx};return type==="monthly"?monthly(all,source,custom):weekly(all,source,custom)}
function vis(events){let wk=new Set(events.filter(e=>e.sourceType==="weekly").map(lkey));return events.filter(e=>!(e.sourceType==="monthly"&&wk.has(lkey(e)))).sort((a,b)=>(`${a.date} ${a.start||"00:00"}`).localeCompare(`${b.date} ${b.start||"00:00"}`))}
function auto(ev,prefs){if(ev.kind==="free"||ev.kind==="halfAM"||ev.kind==="halfPM")return true;if(nameOk(ev,prefs.profile))return true;if(ev.gender==="여자"&&prefs.genderFilter==="남자")return false;if(ev.gender==="남자"&&prefs.genderFilter==="여자")return false;if(partOk(ev.raw,prefs.partText))return true;if(ev.gender==="전체"||ev.gender===prefs.genderFilter)return true;if(prefs.selectedWorks.includes(ev.work))return true;return false}
function esc(t){return String(t||"").replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;")}
function ics(events){let stamp=new Date().toISOString().replace(/[-:]/g,"").split(".")[0]+"Z",lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//SemperPlan//KO","CALSCALE:GREGORIAN","METHOD:PUBLISH","X-WR-CALNAME:SemperPlan"];for(let e of events){let desc=[`원문: ${e.raw}`,e.target?`대상: ${e.target}`:"",e.sourceName?`출처: ${e.sourceName}`:"",`SemperPlan-ID: ${stable(e)}`].filter(Boolean).join("\\n");lines.push("BEGIN:VEVENT",`UID:${stable(e)}@semperplan.local`,`DTSTAMP:${stamp}`,`SUMMARY:${esc(e.title)}`);if(e.allDay){lines.push(`DTSTART;VALUE=DATE:${e.date.replaceAll("-","")}`,`DTEND;VALUE=DATE:${nextDay(e.date).replaceAll("-","")}`)}else{let[y,m,d]=e.date.split("-"),[sh,sm]=e.start.split(":"),[eh,em]=e.end.split(":");lines.push(`DTSTART:${y}${m}${d}T${sh}${sm}00`,`DTEND:${y}${m}${d}T${eh}${em}00`)}if(e.location)lines.push(`LOCATION:${esc(e.location)}`);lines.push(`DESCRIPTION:${esc(desc)}`,"END:VEVENT")}lines.push("END:VCALENDAR");return lines.join("\r\n")}
function dl(name,content,type){let b=new Blob([content],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
function load(){let f={profile:{firstName:"",lastName:""},genderFilter:"남자",partText:"Tenor",selectedWorks:[],customWorksText:"",autoSave:true};try{let r=localStorage.getItem(STORE);if(!r)return f;let p=JSON.parse(r);return{...f,profile:{firstName:p.profile?.firstName||"",lastName:p.profile?.lastName||""},genderFilter:p.genderFilter??"남자",partText:p.partText||"Tenor",selectedWorks:Array.isArray(p.selectedWorks)?p.selectedWorks:[],customWorksText:p.customWorksText||"",autoSave:p.autoSave!==false}}catch{return f}}
function save(p){localStorage.setItem(STORE,JSON.stringify({...p,savedAt:new Date().toISOString()}))}
function makeGoogle(e){let body={summary:e.title,location:e.location||"",description:[`원문: ${e.raw}`,e.target?`대상: ${e.target}`:"",e.sourceName?`출처: ${e.sourceName}`:"",`SemperPlan-ID: ${stable(e)}`].filter(Boolean).join("\n"),extendedProperties:{private:{semperPlan:"true",semperPlanId:stable(e)}}};if(e.allDay){body.start={date:e.date};body.end={date:nextDay(e.date)}}else{body.start={dateTime:`${e.date}T${e.start}:00`,timeZone:TZ};body.end={dateTime:`${e.date}T${e.end}:00`,timeZone:TZ}}return body}
async function req(path,token,opt={}){let r=await fetch(`https://www.googleapis.com/calendar/v3${path}`,{...opt,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(opt.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
async function calId(token){let pt="";do{let d=await req(`/users/me/calendarList${pt?`?pageToken=${encodeURIComponent(pt)}`:""}`,token),f=(d.items||[]).find(c=>c.summary===CAL);if(f)return f.id;pt=d.nextPageToken||""}while(pt);let c=await req("/calendars",token,{method:"POST",body:JSON.stringify({summary:CAL,timeZone:TZ})});return c.id}
async function listRange(id,token,rng){let all=[],pt="";do{let q=new URLSearchParams({maxResults:"2500",singleEvents:"true",showDeleted:"false",timeMin:rng.timeMin,timeMax:rng.timeMax});if(pt)q.set("pageToken",pt);let d=await req(`/calendars/${encodeURIComponent(id)}/events?${q}`,token);all.push(...(d.items||[]));pt=d.nextPageToken||""}while(pt);return all}
async function sync(events,token,progress){let rng=range(events);if(!rng)throw new Error("날짜 범위 없음");let id=await calId(token);progress(`${rng.min}~${rng.max} 기존 일정 확인 중`);let old=await listRange(id,token,rng),keys=new Set(events.map(lkey)),ids=new Set(events.map(stable)),over=old.filter(g=>keys.has(gkey(g))||ids.has(gid(g)));progress(`겹치는 기존 일정 ${over.length}개 삭제 중`);for(let o of over)await req(`/calendars/${encodeURIComponent(id)}/events/${encodeURIComponent(o.id)}`,token,{method:"DELETE"});progress(`최신 일정 ${events.length}개 추가 중`);for(let e of events)await req(`/calendars/${encodeURIComponent(id)}/events`,token,{method:"POST",body:JSON.stringify(makeGoogle(e))});return{deleted:over.length,inserted:events.length,kept:old.length-over.length}}

function App(){let s=useMemo(load,[]),[profile,setProfile]=useState(s.profile),[genderFilter,setGenderFilter]=useState(s.genderFilter),[partText,setPartText]=useState(s.partText),[selectedWorks,setSelectedWorks]=useState(s.selectedWorks),[customWorksText,setCustomWorksText]=useState(s.customWorksText),[autoSave,setAutoSave]=useState(s.autoSave),[events,setEvents]=useState([]),[checked,setChecked]=useState([]),[uploads,setUploads]=useState(0),[token,setToken]=useState(""),[notice,setNotice]=useState(""),[error,setError]=useState(""),[syncing,setSyncing]=useState(false);
let custom=useMemo(()=>customWorksText.split(/[,;\n]/).map(c).filter(Boolean),[customWorksText]),display=useMemo(()=>vis(events),[events]),checkedEvents=useMemo(()=>display.filter(e=>checked.includes(e.id)),[display,checked]),works=useMemo(()=>[...new Set([...events.map(e=>e.work).filter(w=>w&&w!=="chorfrei"),...selectedWorks])].sort((a,b)=>a.localeCompare(b)),[events,selectedWorks]);
useEffect(()=>{if(autoSave)save({profile,genderFilter,partText,selectedWorks,customWorksText,autoSave})},[profile,genderFilter,partText,selectedWorks,customWorksText,autoSave]);
function prefs(){return{profile,genderFilter,partText,selectedWorks}}
function apply(all){let d=vis(all);setChecked(d.filter(e=>auto(e,prefs())).map(e=>e.id))}
async function up(file,type){setError("");try{let idx=uploads+1,parsed=await parsePdf(file,type,idx,custom),all=[...events,...parsed];setEvents(all);apply(all);setUploads(idx);setNotice(`${sourceLabel(type)} PDF에서 ${parsed.length}개 일정을 읽었어요.`)}catch(e){console.error(e);setError("PDF를 읽지 못했어요. 텍스트 기반 PDF인지 확인해 주세요.")}}
function onFile(e,type){let f=e.target.files?.[0];if(f)up(f,type);e.target.value=""}
function reqGoogle(){if(!CID){setError("VITE_GOOGLE_CLIENT_ID가 필요합니다.");return}if(!window.google?.accounts?.oauth2){setError("Google 로그인 스크립트 로딩 중입니다.");return}let client=window.google.accounts.oauth2.initTokenClient({client_id:CID,scope:SCOPE,callback:r=>{if(r.error)setError(`Google 로그인 실패: ${r.error}`);else{setToken(r.access_token);setNotice("Google Calendar 연결 준비 완료.")}}});client.requestAccessToken({prompt:token?"":"consent"})}
async function doSync(){if(!token){setError("먼저 Google Calendar 연결을 해주세요.");return}if(!checkedEvents.length){setError("체크된 일정이 없습니다.");return}let rng=range(checkedEvents),ok=window.confirm(`${rng.min}~${rng.max} 범위에서 체크된 일정과 겹치는 기존 SemperPlan 일정만 삭제하고 최신 ${checkedEvents.length}개 일정을 추가합니다.`);if(!ok)return;try{setSyncing(true);let r=await sync(checkedEvents,token,setNotice);setNotice(`동기화 완료: 겹친 ${r.deleted}개 삭제, 최신 ${r.inserted}개 추가, 안 겹친 ${r.kept}개 유지.`)}catch(e){console.error(e);setError(`동기화 실패: ${e.message}`)}finally{setSyncing(false)}}
function reapply(){apply(events);setNotice("현재 필터 기준으로 체크를 다시 적용했어요.")}
return <main className="page"><header className="hero"><div className="logo"><CalendarPlus size={30}/></div><div><h1>SemperPlan</h1><p>PDF Dienstplan을 한 줄 목록으로 추출하고, 체크한 일정만 Google Calendar에 부분 동기화합니다.</p></div></header>
<section className="grid"><div className="card"><h2>1. PDF 업로드</h2><div className="uploadRow"><label className="upload monthly"><Upload size={18}/> 월간 PDF 업로드<input type="file" accept=".pdf" onChange={e=>onFile(e,"monthly")}/></label><label className="upload weekly"><Upload size={18}/> 주간 PDF 업로드<input type="file" accept=".pdf" onChange={e=>onFile(e,"weekly")}/></label></div><p className="hint">월간과 주간이 같은 시간대에 겹치면 주간만 표시됩니다.</p><button className="ghost" onClick={()=>{setEvents([]);setChecked([]);setUploads(0)}}><RotateCcw size={16}/> 파일/체크 초기화</button></div>
<div className="card"><h2>2. 저장 필터</h2><div className="inputGrid"><label>성<input value={profile.lastName} onChange={e=>setProfile({...profile,lastName:e.target.value})}/></label><label>이름<input value={profile.firstName} onChange={e=>setProfile({...profile,firstName:e.target.value})}/></label><label>파트<input value={partText} onChange={e=>setPartText(e.target.value)} placeholder="Tenor"/></label></div><div className="tabs"><button className={genderFilter==="남자"?"tab active":"tab"} onClick={()=>setGenderFilter("남자")}>남자</button><button className={genderFilter==="여자"?"tab active":"tab"} onClick={()=>setGenderFilter("여자")}>여자</button><button className={genderFilter===""?"tab active":"tab"} onClick={()=>setGenderFilter("")}>전체</button></div><label className="textareaLabel">추가 작품명/별명<textarea value={customWorksText} onChange={e=>setCustomWorksText(e.target.value)} placeholder={"예:\n8. Konzert\nMessa da Requiem"}/></label><div className="tabs"><button className={autoSave?"tab active":"tab"} onClick={()=>setAutoSave(!autoSave)}><Save size={15}/> 자동저장 {autoSave?"ON":"OFF"}</button><button className="tab" onClick={()=>{save({profile,genderFilter,partText,selectedWorks,customWorksText,autoSave});setNotice("필터 저장 완료")}}><Save size={15}/> 지금 저장</button><button className="tab danger" onClick={()=>{localStorage.removeItem(STORE);setNotice("저장값 삭제 완료")}}><Trash2 size={15}/> 저장값 삭제</button></div></div>
<div className="card"><h2>3. Google 동기화</h2><p className="count">{checkedEvents.length}개 체크됨</p><button className="primary" onClick={reqGoogle} disabled={!CID}><LogIn size={18}/> Google Calendar 연결</button><button className="sync" onClick={doSync} disabled={!token||syncing||!checkedEvents.length}><Cloud size={18}/> {syncing?"동기화 중":"겹치는 일정만 교체"}</button><button className="ghost" onClick={()=>dl("semperplan.ics",ics(checkedEvents),"text/calendar;charset=utf-8")} disabled={!checkedEvents.length}><Download size={16}/> .ics 백업</button>{!CID&&<p className="warning"><Lock size={15}/> VITE_GOOGLE_CLIENT_ID 필요</p>}</div></section>
{notice&&<div className="notice"><ShieldCheck size={18}/>{notice}</div>}{error&&<div className="error"><AlertTriangle size={18}/>{error}</div>}
<section className="card worksCard"><div className="sectionHeader"><h2>작품 필터</h2><button className="ghost" onClick={reapply}>현재 필터로 체크 다시 적용</button></div><p className="hint">작품은 처음 전부 해제입니다. 선택한 작품은 저장되어 다음 업로드에 반영됩니다.</p><div className="chips">{works.length===0&&<span className="muted">PDF 업로드 후 작품 버튼이 생성됩니다.</span>}{works.map(w=><button key={w} className={selectedWorks.includes(w)?"chip active":"chip"} onClick={()=>setSelectedWorks(a=>a.includes(w)?a.filter(x=>x!==w):[...a,w])}>{w}</button>)}</div></section>
<section className="card listCard"><div className="sectionHeader"><h2>일정 목록</h2><span className="muted">표시 {display.length}개 / 체크 {checkedEvents.length}개</span></div><div className="list">{display.length===0&&<p className="muted">아직 표시할 일정이 없습니다.</p>}{display.map(ev=><label key={ev.id} className={`row ${ev.kind==="free"||ev.kind==="halfAM"||ev.kind==="halfPM"?"free":""}`}><input type="checkbox" checked={checked.includes(ev.id)} onChange={e=>setChecked(a=>e.target.checked?[...new Set([...a,ev.id])]:a.filter(id=>id!==ev.id))}/><span className="date">{ev.date.slice(5)}</span><span className="time">{ev.allDay?"종일":`${ev.start}-${ev.end}`}</span><span className={`source ${ev.sourceType}`}>{sourceLabel(ev.sourceType)}</span><span className="title">{ev.title}</span><span className="raw">{ev.raw}</span></label>)}</div></section></main>}
createRoot(document.getElementById("root")).render(<App/>);
